server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 1994
  jpa: 
    database: mysql
    show-sql: true
