server:
  port: 9004
spring:
  application:
    name: tensquare-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: 1994
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: localhost