server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 1994
  jpa:
    database: mysql
    show‚Äêsql: true